name: egm722
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2 # the tool's programming language
  - jupyterlab=4.1.4 #Interactive computing environment for Python.
  - folium=0.16.0 #Generates interactive maps with Leaflet.js.
  - pandas=2.2.1 #Handles data manipulation and analysis.
  - matplotlib=3.8.3 #Creates map visualizations.
  - openeo=0.28.0 #Connects to the OpenEO API for Earth observation data processing.
  - rasterio=1.3.9 #Reads and writes raster datasets.
  - numpy=1.26.4 #Performs numerical computations on arrays and matrices.
  - requests=2.31.0 # used fetch data from web services or APIs.
  - geopandas=0.14.3 # Handles geospatial data structures and operations.
  - shapely=2.0.3 # used to manage points, lines and polygon data
  - rasterstats=0.19.0 # used to get statistics from selected areas of rasters


